@startuml lv1_module
skinparam componentStyle rectangle

node "Tales Voice" {
    [MClient] 
    [MServer]
}

component MClient 
component MServer 
component MTTSCloudService

MClient ..> MServer
MClient ..> MTTSCloudService

@enduml