@startuml lv2_component

node Client{
    
    component TaleRepository
    component TaleApiService
    component TTSApiService

    component TaleListViewModel
    component TaleDetailViewModel


    component TaleListView
    component TaleDetailView

    component ClientDB
}



node Server {
    component Router
    component TaleController
    component TaleModel
    component ServerDB
}


Router --> TaleController
TaleController --> TaleModel
TaleModel --> ServerDB

TaleRepository --> ClientDB
TaleRepository --> TaleApiService : TaleListInterface, TaleDetailInterface
TaleDetailViewModel --> TTSApiService : TTSInterface

TaleListViewModel --> TaleRepository
TaleDetailViewModel --> TaleRepository

TaleListViewModel --> TaleListView
TaleDetailViewModel --> TaleDetailView

TaleApiService --> Router
TaleController --> TaleApiService



@enduml


