@startuml lv2_component

node Client {

    component TaleRepository
    component TaleApiService
    component TaleListViewModel
    component TaleDetailViewModel

    component TaleListView
    component TaleDetailView

    component ClientDB
}

node Server {

    component Router
    component TaleController
    component TaleModel
    component ServerDB
}

node TTS3rdParty {
    component TTSCloudService
}

interface TaleListInterface
interface TaleDetailInterface
interface TTSInterface
interface TTS3rdPartyInterface

Router ..> TaleController
TaleController ..> TaleModel
TaleModel ..> ServerDB


TaleRepository ..> ClientDB
TaleRepository ..> TaleApiService

TaleListViewModel ..> TaleRepository
TaleDetailViewModel ..> TaleRepository

TaleListViewModel ..> TaleListView
TaleDetailViewModel ..> TaleDetailView


TTSInterface ..> Router : provided
TaleListInterface ..> Router : provided
TaleDetailInterface ..> Router : provided
TaleApiService --> TaleListInterface : requires
TaleApiService --> TaleDetailInterface : requires
TaleApiService --> TTSInterface :requires

TaleController --> TTS3rdPartyInterface : requires
TTS3rdPartyInterface ..> TTSCloudService : provided

@enduml
