@startuml lv1_execution
skinparam componentStyle rectangle

component ETTSCloudService <<thirdparty>> 
component EAIService <<thirdparty>>

node "Tales Voice" {
    component EClient <<process>>
    component EServer <<process>> 
}

EClient <--> EServer
EClient <--> ETTSCloudService
EServer <--> EAIService

@enduml