@startuml seq_get_tale_list

actor User as user
participant UserInfoView as view
participant UserInfoViewModel as vm
participant TaleRepository as repo
participant ClientDB as db_c

user -> view : 사용자 정보 입력 화면 진입
view --> user : 필요한 사용자 정보 요청 화면 표시
user -> view : 사용자 정보 입력(이름, 성별)
view -> vm : 사용자 정보 저장 요청(이름, 성별)
vm -> repo : 사용자 정보 저장 요청(이름, 성별)
repo -> db_c : 사용자 정보 저장(이름, 성별)
repo --> vm : 저장 완료
vm --> view : 저장 완료 
view --> user : 동화 리스트 화면으로 이동

@enduml