@startuml lv2_component

node Client{
    
    component TaleRepository
    component TaleApiService
    component TTSApiService

    component TaleListViewModel
    component TaleDetailViewModel


    component TaleListView
    component TaleDetailView

    component ClientDB
}



node Server {
    component Router
    component TaleController
    component TaleModel
    component ServerDB
}

node TTS3rdParty {
    component TTSCloudService
}

interface TaleListInterface
interface TaleDetailInterface
interface TTSInterface


Router ..> TaleController
TaleController ..> TaleModel
TaleModel ..> ServerDB

TaleRepository ..> ClientDB
TaleRepository ..> TaleApiService
TaleDetailViewModel ..> TTSApiService

TaleListViewModel ..> TaleRepository
TaleDetailViewModel ..> TaleRepository

TaleListViewModel ..> TaleListView
TaleDetailViewModel ..> TaleDetailView


TTSInterface ..> TTSCloudService : provided
TTSApiService --> TTSInterface : requires

TaleListInterface ..> Router : provided
TaleDetailInterface ..> Router : provided
TaleApiService --> TaleListInterface : requires
TaleApiService --> TaleDetailInterface : requires



@enduml


