@startuml lv2_deployment

skinparam rectangle {
    BorderColor black
    BackgroundColor lightgrey
}

node Client {
    node "<<process>>\nEClient" {
        rectangle "ClientIOThread" as cio
        rectangle "ClientUIThread"
    }
}

node Server {
    
    node "<<process>>\nEServer" as sproc

}
node TTSCloudeService {
  node "<<thirdparty>>\nETTSCloudSerivce" as tts {
    
    }
}

node ChatGPTAPIService {
  node "<<thirdparty>>\nEChatGPTAPIService" as gpt {
    
    }
}
node "ImageServer" as img


cio <--> sproc
cio <--> tts
cio <--> img
sproc <--> gpt

@enduml