@startuml lv2_us01
/'
생성 동화 사용자 피드백 반영
'/
hide footbox

actor User as usr
participant Client as cli
participant Server as svr

usr -> cli : 1. 동화 보기 화면 진입
cli --> usr : 2. 동화 보기 상단\n 피드백 버튼 표시
usr -> cli : 3. 피드백 입력
cli -> svr : 4. 피드백 정보 전달
activate svr
svr -> svr : 5. 피드백 정보 저장
svr --> cli : 6. 피드백 정보 저장 완료
deactivate svr
cli --> usr : 7. 피드백 완료 표시

@enduml