@startuml lv2_us01
/'
사용자 정보 취득
'/
hide footbox

actor User as usr
participant Client as cli
/'participant Server as svr'/

usr -> cli : 1. 사용자 정보 입력 화면 진입 
cli --> usr : 2. 사용자 정보 입력 화면 표시
usr -> cli : 3. 사용자 정보 입력
cli -> cli : 사용자 정보 저장

@enduml